# Generated by Django 5.1.2 on 2025-11-23 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie_details',
            old_name='realese_date',
            new_name='relese_date',
        ),
    ]
